theme = "lynx"
title = "DFWSMUG"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "DFWSMUG"
headline = "Dallas/Fort Worth Systems Management User Group"
image = "images/customLogo.png"
links = [
  { github = "https://github.com/dfwsmug" },
  { twitter = "https://twitter.com/dfwsmug" },
  { facebook = "https://facebook.com/dfwsmug" },
  { eventbrite = { href = "https://www.eventbrite.com/o/dfwsmug-5019563697", text = "Events" } },

]

[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
