theme = "lynx"
title = "DFWSMUG"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "DFWSMUG"
headline = "Dallas/Fort Worth Systems Management User Group"
image = "images/customLogo.png"


[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[imports]]
path = "github.com/jpanther/lynx"
